name: Trigger on Update
description: 'Check if an update is available. If so, trigger a build.'
runs:
  using: composite
  steps:
    - name: Run shell script
      env:
        CI_PROJECT_PATH:    ${{ github.repository }}
        CI_COMMIT_REF_NAME: ${{ github.ref_name }}
        CI_REPOSITORY_URL:  ${{ github.repositoryUrl }}
        GITHUB_TOKEN:       ${{ secrets.GITHUB_TOKEN }}
      working-directory: ${{ github.action_path }}
      run: "./trigger-on-update"
      shell: bash
