name: Trigger on Update
description: 'Check if an update is available. If so, trigger a build.'
inputs:
  repo-owner:
    default: ${{ github.repository_owner }}
  repo-name:
    default: ${{ github.event.repository.name }}
  workflow-id:
    default: 'main.yml'
  ref:
    default: ${{ github.ref_name }}

runs:
  using: composite
  steps:
    - id: update-check
      shell: bash
      env:
        CI_PROJECT_PATH:    ${{ github.repository }}
        CI_COMMIT_REF_NAME: ${{ github.ref_name }}
        CI_REPOSITORY_URL:  ${{ github.repositoryUrl }}
      working-directory: ${{ github.action_path }}
      run: echo "result=$(./update-check)" >>"${GITHUB_OUTPUT}"
    - uses: actions/github-script@v6
      if: steps.update-check.outputs.result == 'outdated'
      with:
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner:       "${{ inputs.repo-owner }}",
            repo:        "${{ inputs.repo-name }}",
            workflow_id: "${{ inputs.workflow-id }}",
            ref:         "${{ inputs.ref }}",
          })
